# configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

# Mailgun credentials from freemium account (login: stephen.krewson@gmail.com)
# (I think the first three fields need to stay in that convention; public key
# is used for email validation in the user model)

heroku_path: 'transhousing.herokuapp.com'

api_key:     'key-e1559839d40f484a76d1c572c8336525'
password:    'a38a2eac64309291589605143c18d163'
domain:      'sandboxbd973932489c42a6aa4cae41aee75c6a.mailgun.org'
username:    'postmaster@sandboxbd973932489c42a6aa4cae41aee75c6a.mailgun.org'
pub_key:     'pubkey-d005c8be2308c95c34d7b9924a2b7fa7'

# Twilio-Ruby credentials (login: stephen.krewson@yale.edu)
account_sid:  'AC829c62c86b2172157b9e0fd898118f63'
auth_token:   '718491a6199e42faff449704b61bfc9e'
twilio_num:   '+15015022331'

# Recaptcha (ambethia's gem); the names are required by the gem
RECAPTCHA_PUBLIC_KEY:  '6Ld1TwUTAAAAAOgV0Vm8UIT7zn-kEiF-Sa3gX6gK'
RECAPTCHA_PRIVATE_KEY: '6Ld1TwUTAAAAAD2mUqF3B-n35QsxoUEd1UPJsAte'



# N.B. Figaro stashes these in ENV['string']
